name: Hola mundo

on:
  workflow_dispatch:

jobs:
  hola:
    runs-on: ubuntu-latest
    steps:
      - name: Saludar
        run: echo "Hola mundo"
      - name: Descargar codigo
        uses: actions/checkout@v4
      - name: Mostrar carpeta
        run: pwd
      - name: Listar archivos
        run: ls -la
      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Verificar Node
        run: node --version
