name: Publicar App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publicar:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: clase_08_27/tic-tac-toe

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: clase_08_27/tic-tac-toe/package-lock.json

      - name: Instalar dependencias
        run: npm ci

      - name: Construir app
        run: npm run build

      - name: Validar artefacto
        run: |
          test -d dist
          test -f dist/index.html
      - name: Configurar Github Pages
        uses: actions/configure-pages@v5
      - name: Subir dist 
        uses: actions/upload-pages-artifact@v4
        with:
          name: aplicacion-web
          path: clase_08_27/tic-tac-toe/dist

      - name: publicar
        uses: actions/deploy-pages@v4
