name: Vite Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: clase_08_27/tic-tac-toe

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: clase_08_27/tic-tac-toe/package-lock.json

      - name: Instalar dependencias
        run: npm ci

      - name: Construir proyecto
        run: npm run build

      - name: Guardar aplicacion
        uses: actions/upload-artifact@v4
        with:
          name: aplicacion-web
          path: clase_08_27/tic-tac-toe/dist
